apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cleanup-task
spec:
  steps:
    - name: cleanup
      image: registry.access.redhat.com/openshift4/ose-cli
      script: |
        #!/bin/bash
        oc delete pvc --all --force --grace-period=0 || true
        oc delete pods --all --force --grace-period=0 || true
        oc delete services --all --force --grace-period=0 || true
        oc delete deployments --all --force --grace-period=0 || true
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: nose-test-task
spec:
  steps:
    - name: fetch-repository
      image: alpine/git
      script: |
        #!/bin/sh
        git clone $(params.git-url) $(workspaces.source.path)
        cd $(workspaces.source.path)
        git checkout $(params.git-revision)
    
    - name: run-tests
      image: python:3.8
      script: |
        #!/bin/sh
        cd $(workspaces.source.path)
        pip install nose
        nosetests tests/ --with-xunit --xunit-file=test-results.xml
      volumeMounts:
        - name: test-results
          mountPath: /workspace/test-results
  volumes:
    - name: test-results
      emptyDir: {}
  workspaces:
    - name: source
      description: The git repository to test
  params:
    - name: git-url
      type: string
      description: The git repository URL
    - name: git-revision
      type: string
      description: The git revision to test
      default: "main" 